name: 'SPOTIFY_ANALYSIS'
version: '1.0.0'

profile: 'SPOTIFY_ANALYSIS'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  SPOTIFY_ANALYSIS:
    +database: SPOTIFY
    +schema: SPOTIFY_LANDING
    SPOTIFY_STAGE:
      +materialized: table